name: Release to CocoaPods

on:
  release:
    types:
      - published

permissions:
  contents: write

env:
  PODSPEC_PATH: ./TempoSDK.podspec

jobs:
  validate-update-podspec:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      # Check the podspec file for any issues
      - name: Lint Podspec
        run: |
          pod spec lint ${{ env.PODSPEC_PATH }} --allow-warnings --verbose

      # Update the semantic version number in the .TempoSDK.podspec file
      - name: Update Version
        shell: pwsh
        run: |
          $version = "'${{ github.event.release.tag_name }}'"
          $podspec = Get-Content "$env:PODSPEC_PATH"
          $podspec = $podspec -replace '^(.*spec.version.*)(''.*'')$', "`$1$version"
          $podspec | Set-Content -Path "$env:PODSPEC_PATH" -Force

      # Checks to see if the .podspec needs to be pushed
      - name: Diff .podspec
        shell: pwsh
        run: |
          $diff = git diff --name-only ${{ env.PODSPEC_PATH }}
          if ($Null -ne $diff) {
              Write-Output "diff=true" >> $env:GITHUB_OUTPUT
          }
          else {
              Write-Output "diff=false" >> $env:GITHUB_OUTPUT
          }

      # Push the formatted files if required
      - name: Push Changes
        if: ${{ env.diff == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          branch: main

  push-pod:
    needs: validate-update-podspec
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      # Using the podspec, push the latest version of the pod to CocoaPod
      - name: Push Pod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push ${{ env.PODSPEC_PATH }} --allow-warnings --verbose
