name: Release Drafter

on:
  push:
    branches:
      - main
    paths-ignore:
      - TempoSDK.podspec
      - TempoSDK/Constants.swift

  # pull_request event is required for autolabeler
  pull_request:
    # Only following types are supported
    types: [opened, reopened, synchronize]

permissions:
  # Required to create a GitHub release & update version files
  contents: write

env:
  PODSPEC_PATH: ./TempoSDK.podspec
  CONSTANTS_PATH: ./TempoSDK/Constants.swift

jobs:
  update-release-draft:
    permissions:
      # Required for autolabeler
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main

      - name: Set Version
        id: set-version
        if: github.event_name != 'pull_request'
        shell: pwsh
        run: |
          $version = "${{ steps.release-drafter.outputs.tag_name }}"
          Write-Output "Release version: $version"
          Write-Output "version=$version" >> $env:GITHUB_OUTPUT

  update-podspec:
    needs: update-release-draft
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout main branch, with full history using PAT
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.REPO_WRITE_PAT }}

      # Update the semantic version number in the .podspec and Constants.swift files
      - name: Update Versions
        shell: pwsh
        run: |
          $version = "${{ needs.update-release-draft.outputs.version }}"
          
          Write-Output "Attempting to update podspec version to $version"
          $podspec = Get-Content "$env:PODSPEC_PATH"
          $podspec = $podspec -replace '^(.*spec.version.*)(''.*'')$', "`$1'$version'"
          
          Write-Output "Adjusted podspec:`n$podspec"
          $podspec | Set-Content -Path "$env:PODSPEC_PATH" -Force
          
          Write-Output "Attempting to update Constants.swift version to $version"
          $constants = Get-Content "$env:CONSTANTS_PATH"
          $constants = $constants -replace '^(.*SDK_VERSIONS.*)(".*")$', "`$1`"$version`""
          
          Write-Output "Adjusted Constants.swift:`n$constants"
          $constants | Set-Content -Path "$env:CONSTANTS_PATH" -Force
      

      # Stage and commit the updated .podspec file
      - name: Stage & Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Updated .podspec & Constants.swift versions"

      # Force push the updated podspec file using PAT to bypass branch protection
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_WRITE_PAT }}
          force_with_lease: true
